apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  namespace: sre
spec:
  serviceName: loki
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki:2.9.3
        ports:
        - containerPort: 3100
        volumeMounts:
        - name: storage
          mountPath: /loki
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
