apiVersion: v1
kind: Namespace
metadata:
  name: databases
  labels:
    name: databases
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
