apiVersion: v1
kind: Namespace
metadata:
  name: sre
  labels:
    name: sre
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
